apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: test-namespace
spec:
  limits:
  - default:
      cpu: 1
      memory: 500Mi
    defaultRequest:
      cpu: 0.4
      memory: 250Mi
    type: Container
