apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-replicaset-deployment
  labels:
    app: my-jenkins
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-jenkins
  template:
    metadata:
      labels:
        app: my-jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
      tolerations:
        - key: "name"
          operator: "Equal"
          value: "qa"
          effect: "NoExecute"
