apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-replicaset-deployment
  labels:
    app: my-jenkins
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-jenkins
  template:
    metadata:
      labels:
        app: my-jenkins
    spec:
      volumes: 
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: local-pvc 
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-volume 
      securityContext:
        runAsUser: 0
        fsGroup: 0
