apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice-nodeport-test
spec:
  type: NodePort
  selector:
    my-pod: Jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003

