---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins1
  labels:
    my-pod: Jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:latest
---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice-loadbalancer
spec:
  type: LoadBalancer
  selector:
    my-pod: Jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
