apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice-extrenal-ip
spec:
  selector:
    my-pod: Jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8080
  externalIPs:
    - 172.31.45.157
