apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-replicaset
  namespace: default
spec:
  replicas: 2
  selector:
        matchLabels:
               my-pod: my-jenkins
  template:
    metadata:
      labels:
        my-pod: my-jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest

---
apiVersion: v1
kind: Service
metadata:
  name: jenkinsservice-nodeport
spec:
  type: NodePort
  selector:
    my-pod: my-jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
