apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-replicaset-deployment
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replica}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxsurge}}
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-jenkins
  template:
    metadata:
      labels:
        app: my-jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:latest
